// {
// 	"_id" : ObjectId("5c16e18bc69fe0001838d313"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "mauri123456",
// 	"contrasenia" : "$2a$10$ROxmzL/841if9pW7fkDnA.aJdSPEetcsPZUoL5a7mMhf9s.8ogYkq",
// 	"cartas" : [
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49dd",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "dakimakura",
// 			"nombre_completo" : "Dakimakura",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49de",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "mochila_pegajosa",
// 			"nombre_completo" : "Mochila pegajosa",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49df",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "catapulta",
// 			"nombre_completo" : "Catapulta",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e0",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_base",
// 			"nombre_completo" : "Jugador de Football Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e1",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_medio",
// 			"nombre_completo" : "Jugador de Football Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e2",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_estrella",
// 			"nombre_completo" : "Jugador de Football Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e3",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_base",
// 			"nombre_completo" : "Bailarín Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e4",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_medio",
// 			"nombre_completo" : "Bailarín Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e5",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_estrella",
// 			"nombre_completo" : "Bailarín Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e6",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_base",
// 			"nombre_completo" : "Punk Girl Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e7",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_media",
// 			"nombre_completo" : "Punk Girl Media",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e8",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_estrella",
// 			"nombre_completo" : "Punk Girl Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e9",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "Drone_2_Idle",
// 			"nombre_completo" : "Drone 2.0 Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ea",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "drone_idle",
// 			"nombre_completo" : "Drone Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49eb",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_cierra",
// 			"nombre_completo" : "Mochila cierra",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ec",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_honda",
// 			"nombre_completo" : "Mochila Honda",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ed",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_mina",
// 			"nombre_completo" : "Mochila Mina",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		}
// 	],
// 	"__v" : 1
// }
// {
// 	"_id" : ObjectId("5c16e255c69fe0001838d314"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "mauri1234567",
// 	"contrasenia" : "$2a$10$Vr8SAVv4BtwXpeegXFuePe4QuUkGxzeEHBpi2cJ6IvMJ1HN3IcFu2",
// 	"cartas" : [ ],
// 	"__v" : 0
// }
// {
// 	"_id" : ObjectId("5c16e89dc69fe0001838d315"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "a2",
// 	"contrasenia" : "$2a$10$t7qvBblkufN3uVF29XuEb.SY27dRYyoRp9XVZ.NiZHyxq2tZcBAIG",
// 	"cartas" : [
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49dd",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "dakimakura",
// 			"nombre_completo" : "Dakimakura",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49de",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "mochila_pegajosa",
// 			"nombre_completo" : "Mochila pegajosa",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49df",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "catapulta",
// 			"nombre_completo" : "Catapulta",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e0",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_base",
// 			"nombre_completo" : "Jugador de Football Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e1",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_medio",
// 			"nombre_completo" : "Jugador de Football Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e2",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_estrella",
// 			"nombre_completo" : "Jugador de Football Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e3",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_base",
// 			"nombre_completo" : "Bailarín Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e4",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_medio",
// 			"nombre_completo" : "Bailarín Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e5",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_estrella",
// 			"nombre_completo" : "Bailarín Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e6",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_base",
// 			"nombre_completo" : "Punk Girl Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e7",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_media",
// 			"nombre_completo" : "Punk Girl Media",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e8",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_estrella",
// 			"nombre_completo" : "Punk Girl Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e9",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "Drone_2_Idle",
// 			"nombre_completo" : "Drone 2.0 Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ea",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "drone_idle",
// 			"nombre_completo" : "Drone Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49eb",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_cierra",
// 			"nombre_completo" : "Mochila cierra",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ec",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_honda",
// 			"nombre_completo" : "Mochila Honda",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ed",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_mina",
// 			"nombre_completo" : "Mochila Mina",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		}
// 	],
// 	"__v" : 1
// }
// {
// 	"_id" : ObjectId("5c180519c69fe0001838d316"),
// 	"puntos" : 0,
// 	"nivel" : 10,
// 	"nombreusuario" : "c1",
// 	"contrasenia" : "$2a$10$kC.tKMq2Toc7W69Nm9n/z.FooqhqzJYk1ODQ5IQzYr953YOY.eKfS",
// 	"cartas" : [
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49dd",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "dakimakura",
// 			"nombre_completo" : "Dakimakura",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49de",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "mochila_pegajosa",
// 			"nombre_completo" : "Mochila pegajosa",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49df",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "catapulta",
// 			"nombre_completo" : "Catapulta",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e0",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_base",
// 			"nombre_completo" : "Jugador de Football Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e1",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_medio",
// 			"nombre_completo" : "Jugador de Football Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e2",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_estrella",
// 			"nombre_completo" : "Jugador de Football Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e3",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_base",
// 			"nombre_completo" : "Bailarín Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e4",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_medio",
// 			"nombre_completo" : "Bailarín Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e5",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_estrella",
// 			"nombre_completo" : "Bailarín Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e6",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_base",
// 			"nombre_completo" : "Punk Girl Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e7",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_media",
// 			"nombre_completo" : "Punk Girl Media",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e8",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_estrella",
// 			"nombre_completo" : "Punk Girl Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e9",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "Drone_2_Idle",
// 			"nombre_completo" : "Drone 2.0 Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ea",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "drone_idle",
// 			"nombre_completo" : "Drone Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49eb",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_cierra",
// 			"nombre_completo" : "Mochila cierra",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ec",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_honda",
// 			"nombre_completo" : "Mochila Honda",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ed",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_mina",
// 			"nombre_completo" : "Mochila Mina",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		}
// 	],
// 	"__v" : 1
// }
// {
// 	"_id" : ObjectId("5c18328fc69fe0001838d317"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "a4",
// 	"contrasenia" : "$2a$10$u.qsr3HkDtVFQM6CjJ7B2OowVaNp2zwu1JlbDCQtfZn/ZM93yJp7.",
// 	"cartas" : [
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49dd",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "dakimakura",
// 			"nombre_completo" : "Dakimakura",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49de",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "mochila_pegajosa",
// 			"nombre_completo" : "Mochila pegajosa",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49df",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "catapulta",
// 			"nombre_completo" : "Catapulta",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e0",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_base",
// 			"nombre_completo" : "Jugador de Football Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e1",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_medio",
// 			"nombre_completo" : "Jugador de Football Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e2",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_estrella",
// 			"nombre_completo" : "Jugador de Football Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e3",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_base",
// 			"nombre_completo" : "Bailarín Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e4",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_medio",
// 			"nombre_completo" : "Bailarín Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e5",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_estrella",
// 			"nombre_completo" : "Bailarín Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e6",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_base",
// 			"nombre_completo" : "Punk Girl Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e7",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_media",
// 			"nombre_completo" : "Punk Girl Media",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e8",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_estrella",
// 			"nombre_completo" : "Punk Girl Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e9",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "Drone_2_Idle",
// 			"nombre_completo" : "Drone 2.0 Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ea",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "drone_idle",
// 			"nombre_completo" : "Drone Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49eb",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_cierra",
// 			"nombre_completo" : "Mochila cierra",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ec",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_honda",
// 			"nombre_completo" : "Mochila Honda",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ed",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_mina",
// 			"nombre_completo" : "Mochila Mina",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		}
// 	],
// 	"__v" : 1
// }
// {
// 	"_id" : ObjectId("5c186344c69fe0001838d318"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "b3",
// 	"contrasenia" : "$2a$10$ptM14LJp6IwFVSMvD37ND.yEeSxKDdOzSgfOdfDfUDtVonNVeniB6",
// 	"cartas" : [ ],
// 	"__v" : 0
// }
// {
// 	"_id" : ObjectId("5c1931a6c69fe0001838d319"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "a1",
// 	"contrasenia" : "$2a$10$Vy.p3ebfEJ.coHfZa1iFiu1FlZnRSaXA3X.cBwbeAsV1wj7v3ckJ.",
// 	"cartas" : [
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49dd",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "dakimakura",
// 			"nombre_completo" : "Dakimakura",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49de",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "mochila_pegajosa",
// 			"nombre_completo" : "Mochila pegajosa",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49df",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "catapulta",
// 			"nombre_completo" : "Catapulta",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e0",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_base",
// 			"nombre_completo" : "Jugador de Football Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e1",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_medio",
// 			"nombre_completo" : "Jugador de Football Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e2",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_estrella",
// 			"nombre_completo" : "Jugador de Football Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e3",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_base",
// 			"nombre_completo" : "Bailarín Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e4",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_medio",
// 			"nombre_completo" : "Bailarín Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e5",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_estrella",
// 			"nombre_completo" : "Bailarín Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e6",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_base",
// 			"nombre_completo" : "Punk Girl Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e7",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_media",
// 			"nombre_completo" : "Punk Girl Media",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e8",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_estrella",
// 			"nombre_completo" : "Punk Girl Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e9",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "Drone_2_Idle",
// 			"nombre_completo" : "Drone 2.0 Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ea",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "drone_idle",
// 			"nombre_completo" : "Drone Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49eb",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_cierra",
// 			"nombre_completo" : "Mochila cierra",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ec",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_honda",
// 			"nombre_completo" : "Mochila Honda",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ed",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_mina",
// 			"nombre_completo" : "Mochila Mina",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		}
// 	],
// 	"__v" : 1
// }
// {
// 	"_id" : ObjectId("5c1950a7c69fe0001838d31c"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "a5",
// 	"contrasenia" : "$2a$10$cbF/YjGD0rKwwjEGRfdLo.aklT5zu5/sGorLENFp/S7aShLt0BWw6",
// 	"cartas" : [ ],
// 	"__v" : 0
// }
// {
// 	"_id" : ObjectId("5c196dc9c69fe0001838d31d"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "a6",
// 	"contrasenia" : "$2a$10$.7F9KS9pKqXRmmo4F8Y/OeyleM1a09TwR2mH6i94m1.z6fQnnqYd.",
// 	"cartas" : [ ],
// 	"__v" : 0
// }
// {
// 	"_id" : ObjectId("5c197ba1c69fe0001838d31f"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "a7",
// 	"contrasenia" : "$2a$10$42wyOGrWVUXwZDMj5UjorOveYvChLCn7PwsCRJC47fuNuy1AHney6",
// 	"cartas" : [
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49dd",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "dakimakura",
// 			"nombre_completo" : "Dakimakura",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49de",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "mochila_pegajosa",
// 			"nombre_completo" : "Mochila pegajosa",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49df",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "catapulta",
// 			"nombre_completo" : "Catapulta",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e0",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_base",
// 			"nombre_completo" : "Jugador de Football Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e1",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_medio",
// 			"nombre_completo" : "Jugador de Football Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e2",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_estrella",
// 			"nombre_completo" : "Jugador de Football Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e3",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_base",
// 			"nombre_completo" : "Bailarín Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e4",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_medio",
// 			"nombre_completo" : "Bailarín Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e5",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_estrella",
// 			"nombre_completo" : "Bailarín Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e6",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_base",
// 			"nombre_completo" : "Punk Girl Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e7",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_media",
// 			"nombre_completo" : "Punk Girl Media",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e8",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_estrella",
// 			"nombre_completo" : "Punk Girl Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e9",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "Drone_2_Idle",
// 			"nombre_completo" : "Drone 2.0 Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ea",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "drone_idle",
// 			"nombre_completo" : "Drone Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49eb",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_cierra",
// 			"nombre_completo" : "Mochila cierra",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ec",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_honda",
// 			"nombre_completo" : "Mochila Honda",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ed",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_mina",
// 			"nombre_completo" : "Mochila Mina",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		}
// 	],
// 	"__v" : 1
// }
// {
// 	"_id" : ObjectId("5c1982b3c69fe0001838d324"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "a8",
// 	"contrasenia" : "$2a$10$CbmPkfzDWsH8m1h8oIyET.Q.BC7.xhe/eWzTwCwelnDd/Py2pqKeC",
// 	"cartas" : [
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49dd",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "dakimakura",
// 			"nombre_completo" : "Dakimakura",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49de",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "mochila_pegajosa",
// 			"nombre_completo" : "Mochila pegajosa",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49df",
// 			"tipo" : "nerd-weabooLord",
// 			"nombre" : "catapulta",
// 			"nombre_completo" : "Catapulta",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e0",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_base",
// 			"nombre_completo" : "Jugador de Football Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e1",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_medio",
// 			"nombre_completo" : "Jugador de Football Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e2",
// 			"tipo" : "sicario-jugadorfootball",
// 			"nombre" : "jugador_football_estrella",
// 			"nombre_completo" : "Jugador de Football Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e3",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_base",
// 			"nombre_completo" : "Bailarín Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e4",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_medio",
// 			"nombre_completo" : "Bailarín Medio",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e5",
// 			"tipo" : "sicario-bailarin",
// 			"nombre" : "bailarin_estrella",
// 			"nombre_completo" : "Bailarín Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 5,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e6",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_base",
// 			"nombre_completo" : "Punk Girl Base",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e7",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_media",
// 			"nombre_completo" : "Punk Girl Media",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e8",
// 			"tipo" : "sicario-punk-girl",
// 			"nombre" : "punk_girl_estrella",
// 			"nombre_completo" : "Punk Girl Estrella",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49e9",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "Drone_2_Idle",
// 			"nombre_completo" : "Drone 2.0 Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ea",
// 			"tipo" : "nerd-it-guy",
// 			"nombre" : "drone_idle",
// 			"nombre_completo" : "Drone Idle",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49eb",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_cierra",
// 			"nombre_completo" : "Mochila cierra",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ec",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_honda",
// 			"nombre_completo" : "Mochila Honda",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		},
// 		{
// 			"nivel" : 1,
// 			"aprendida" : false,
// 			"_id" : "5c16db52c3dad600331c49ed",
// 			"tipo" : "nerd-punk-girl",
// 			"nombre" : "mochila_mina",
// 			"nombre_completo" : "Mochila Mina",
// 			"danio" : 20,
// 			"costo_para_desbloquear" : 2,
// 			"velocidad" : "10",
// 			"limite_nivel" : 5
// 		}
// 	],
// 	"__v" : 1
// }
// {
// 	"_id" : ObjectId("5c198e933c19a9001155b737"),
// 	"puntos" : 0,
// 	"nivel" : 1,
// 	"nombreusuario" : "mauri123",
// 	"contrasenia" : "$2a$10$kxywQKfNPYmcF6a5wninNeel2.RQww4OOHkYQKLtyMh.CyTG765e2",
// 	"cartas" : [ ],
// 	"__v" : 0
// }